### ISSUE TITLE
collaborate.

### ISSUE THREAD

**Issue by streghstreek** [DonyaOS/DonyaOS.github.io#5]

**Comment by BaseMax** [comment]
Dear,

Join team by send a message at there https://github.com/DonyaOS/Donya/issues/4 @streghstreek  

Please introduce yourself there, And write down what you can do to help and what your experiences are.

Best
Max

**Comment by jbampton** [comment]
Hey @BaseMax  I already sent the invite

**Comment by streghstreek** [comment]
Hi @jbampton Thank you we already joined on github community

Happy nice days.

**Comment by BaseMax** [comment]
Thanks
Yes, it is good, it is not a problem. But introduce themselves. So that other friends know him better and know where we can get help from him.
